### Jobs ###

version: 2
jobs:
  verify:
    docker:
      - image: circleci/ruby:latest
    steps:
      - checkout
      - run:
          name: Installing rubygems markdown lint
          command: gem install mdl
      - run:
          name: Checking formatting of markdown files
          command: for i in `find . -maxdepth 1 -name "*.md"`; do mdl -r ~MD013,~MD007 $i; done

### Workflows ###

workflows:
  version: 2
  lint:
    jobs:
      - verify

